theme: jekyll-theme-minimal
title: Sternenfisch's homepage
description: Bookmark this to keep an eye on my project updates! Namely my attempts to generate GNATPROVE verified Ada SPARK Code from Open Source Reasearch Papers with the aid of Mistral Code.
